### ISSUE TITLE
De Lijn GTFS-dump is not updating

### ISSUE THREAD

**Issue by JorenVos** [iRail/iRail#451]
As you can see on https://gtfs.irail.be/de-lijn/, the GTFS-dump is out-of-date since the 25th of January; is it possible to fix this?

Thanks in advance!

**Comment by Muspah** [comment]
Not exactly what you're looking for, and I'm unable to fix this issue, but if you're in need of a recent GTFS zip from DeLijn, we're mirroring too: https://data.ovdata.nl/belgie/GTFS/DELIJN/

**Comment by pietercolpaert** [comment]
This is fixed

**Comment by JorenVos** [comment]
When I check the zip-file at https://gtfs.irail.be/de-lijn/, it's still the old one from the 25th of January. I think it's not fixed yet...
